const generos = [
    'Ação',
    'Artes Marciais',
    'Aventura',
    'Comédia',
    'Demônios',
    'Drama',
    'Ecchi',
    'Escolar',
    'Esporte',
    'Fantasia',
    'Ficção científica',
    'Harém',
    'Histórico',
    'Horror',
    'Jogo',
    'Light Novel',
    'Magia',
    'Mecha',
    'Militar',
    'Mistério',
    'Musical',
    'Romance',
    'Samurai',
    'Seinen',
    'Sem Censura',
    'Shoujo',
    'Shounen',
    'Slice Of Life',
    'Sobrenatural',
    'Super Poderes',
    'Suspense',
    'Terror',
    'Yaoi',
    'Yuri',
]
export default generos;